# Generated by Django 3.1.3 on 2020-11-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50, verbose_name='Nick name')),
                ('avatar', models.ImageField(default='uploads/user_avatar.png', upload_to='uploads/', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.PositiveIntegerField(default=0, verbose_name='Count likes')),
                ('count_dislikes', models.PositiveIntegerField(default=0, verbose_name='Count dislikes')),
                ('rating', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='RatingAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_opinion', models.BooleanField(verbose_name='User like it')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rating')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='authors',
            field=models.ManyToManyField(editable=False, through='app.RatingAuthors', to='app.Profile', verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Date of creating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Author')),
                ('rating', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='app.rating')),
                ('tags', models.ManyToManyField(to='app.Tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Date of creating')),
                ('flag_correct_answer', models.BooleanField(verbose_name='Is correct')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Author')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Question')),
                ('rating', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='app.rating')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
